### PR TITLE
fix(no-done-callback): fix regression with it.each

### LINKED ISSUE #709: test.each no-done-callback false positive in version 24.1.1
Plugin version: 24.1.1
Last working version: 24.1.0
Rule **jest/no-done-callback** has false positives with test.each
```
test.each`
  size   | chunkSize    | sum
  ${50}  | ${undefined} | ${(50 * 49) / 2}
`(
  "sums array indices of size $size with chunkSize=$chunkSize => $sum",
  async ({size, chunkSize, sum}) => {
    await expect(
      reduce(new Array(size).fill(0).map((v, index) => index), (ret, it, index) => ret + index, 0, chunkSize)
    ).resolves.toBe(sum);
  }
);
```

### PR DESCRIPTION
**Pull request by k-yle**
Closes #709

my recent PR #701 caused a false positive for `no-done-callback` when used with jest-each (sorry!)

`it.each` uses the first argument for options, and the second argument for the done callback.

This PR fixes the bug and adds test cases for it.each

### CODE REVIEW

File: src/rules/no-done-callback.ts [hunk 1]
```diff
@@ -41,17 +50,21 @@ export default createRule({
   create(context) {
     return {
       CallExpression(node) {
-        const callback = findCallbackArg(node);
+        // done is the second argument for it.each, not the first
+        const isJestEach = !!getNodeName(node.callee)?.endsWith('.each');
+
+        const callback = findCallbackArg(node, isJestEach);
+        const callbackArgIndex = +isJestEach;
```
Comment (G-Rath) [inline src/rules/no-done-callback.ts:57]:
```suggestion
        const callbackArgIndex = Number(isJestEach);
```

File: src/rules/no-done-callback.ts [hunk 2]
```diff
@@ -2,11 +2,20 @@ import {
...
+  isFunction,
+  isHook,
+  isTestCase,
+} from './utils';
 
 const findCallbackArg = (
   node: TSESTree.CallExpression,
+  isJestEach: boolean,
 ): TSESTree.CallExpression['arguments'][0] | null => {
+  if (isJestEach) return node.arguments[1];
```
Comment (G-Rath) [inline src/rules/no-done-callback.ts:17]:
```suggestion
  if (isJestEach) {
    return node.arguments[1];
  }
```

**Review by G-Rath — APPROVED** [review]

File: src/rules/no-done-callback.ts [hunk 3]
```diff
@@ -41,17 +52,21 @@ export default createRule({
   create(context) {
     return {
       CallExpression(node) {
-        const callback = findCallbackArg(node);
+        // done is the second argument for it.each, not the first
+        const isJestEach = !!getNodeName(node.callee)?.endsWith('.each');
```
Comment (SimenB) [inline src/rules/no-done-callback.ts:56]:
```suggestion
        const isJestEach = getNodeName(node.callee)?.endsWith('.each') != null;
```

Comment (G-Rath) [reply src/rules/no-done-callback.ts:56]: Don't we have `eqeqeq` on? 🤔

Comment (k-yle) [reply src/rules/no-done-callback.ts:56]: `.endsWith('.each')` returns `boolean`, I'm not sure if this has the same effect

**Comment by G-Rath** [comment]
I mucked up my commit, so it needs to be reworded 🤦‍♂️

**Comment by k-yle** [comment]
@G-Rath shall I amend that commit? I don't see what's wrong with the commit message though

File: src/rules/no-done-callback.ts (hunk 3 above)
Comment (SimenB) [reply src/rules/no-done-callback.ts:56]:
```suggestion
        const isJestEach = getNodeName(node.callee)?.endsWith('.each') ?? false;
```

**Comment by G-Rath** [comment]
@k-yle yes please - it's the capital letter, changing it to `apply` should fix it :)

File: src/rules/no-done-callback.ts (hunk 3 above)
Comment (SimenB) [reply src/rules/no-done-callback.ts:56]: > Don't we have `eqeqeq` on? 🤔

I assume we allow "smart" equality which has exceptions for `== null`. regardless, that was the wrong thing 😀

**Comment by voda** [comment]
@k-yle I found another false positive, reported in #710
