### PR TITLE
fix(no-disabled-tests): switch to using jest function call parser

### LINKED ISSUE #1115: [no-disabled-tests] does not support `@jest/globals`
Currently this rule uses AST selectors & `getNodeName` to target Jest functions, which means it doesn't support `@jest/globals` - it should be switched to using our scoped utils.

### PR DESCRIPTION
**Pull request by G-Rath**
To be merged after #1122 is landed

Resolves #1115

### CODE REVIEW

File: src/rules/no-disabled-tests.ts [hunk 1]
```diff
@@ -27,40 +30,49 @@ export default createRule({
...
     return {
-      'CallExpression[callee.name="describe"]'() {
-        suiteDepth++;
-      },
-      'CallExpression[callee.name=/^(it|test)$/]'() {
-        testDepth++;
-      },
       'CallExpression[callee.name=/^(it|test)$/][arguments.length<2]'(node) {
         context.report({ messageId: 'missingFunction', node });
       },
```
Comment (G-Rath) [inline src/rules/no-disabled-tests.ts:35]: ugh I realised I missed this somehow - will do a follow-up PR
