### PR TITLE
fix(prefer-expect-assertions): report on concise arrow functions

### LINKED ISSUE #1204: Results of weekly scheduled smoke test
Detected 27 ESLint reports and/or crashes. 
Scanned 1756 repositories.

Rules:
-   `jest/prefer-expect-assertions`

<details>
    <summary>Click to expand</summary>

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/facebook/draft-js/src/component/utils/exploration/__tests__/DraftTreeInvariants-test.js:22 Rule: "jest/prefer-expect-assertions"`
-   Path: `facebook/draft-js/src/component/utils/exploration/__tests__/DraftTreeInvariants-test.js`
-   [Link](https://github.com/facebook/draft-js/blob/HEAD/src/component/utils/exploration/__tests__/DraftTreeInvariants-test.js#L22)

```js
  20 |
  21 | test('single block', () =>
> 22 |   expect(
  23 |     DraftTreeInvariants.isValidTree(
  24 |       Immutable.OrderedMap({
  25 |         A: new ContentBlockNode({
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/facebook/draft-js/src/component/utils/exploration/__tests__/DraftTreeInvariants-test.js:22
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/clear-cache/__tests__/clearCache.test.js:11 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/clear-cache/__tests__/clearCache.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/clear-cache/__tests__/clearCache.test.js#L11)

```js
   9 | 'use strict';
  10 |
> 11 | test('stub', () => expect(1).toBe(1));
  12 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/clear-cache/__tests__/clearCache.test.js:11
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/custom-matcher-stack-trace/__tests__/asynchronous.test.js:11 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/custom-matcher-stack-trace/__tests__/asynchronous.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/custom-matcher-stack-trace/__tests__/asynchronous.test.js#L11)

```js
   9 |
  10 | test('showing the stack trace for an async matcher', () =>
> 11 |   expect(true).toThrowCustomAsyncMatcherError());
  12 |
  13 | function toThrowCustomAsyncMatcherError() {
  14 |   const message = () =>
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/custom-matcher-stack-trace/__tests__/asynchronous.test.js:11
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/env-test/__tests__/env.test.js:11 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/env-test/__tests__/env.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/env-test/__tests__/env.test.js#L11)

```js
   9 | console.log(global.window ? 'WINDOW' : 'NO WINDOW');
  10 |
> 11 | test('stub', () => expect(1).toBe(1));
  12 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/env-test/__tests__/env.test.js:11
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/expect-async-matcher/__tests__/failure.test.js:13 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/expect-async-matcher/__tests__/failure.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/expect-async-matcher/__tests__/failure.test.js#L13)

```js
  11 |
  12 | it('fail with expected non promise values', () =>
> 13 |   expect([1]).toHaveLengthAsync(Promise.resolve(2)));
  14 |
  15 | it('fail with expected non promise values and not', () =>
  16 |   expect([1, 2]).not.toHaveLengthAsync(Promise.resolve(2)));
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/expect-async-matcher/__tests__/failure.test.js:13
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/expect-async-matcher/__tests__/success.test.js:13 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/expect-async-matcher/__tests__/success.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/expect-async-matcher/__tests__/success.test.js#L13)

```js
  11 |
  12 | it('works with expected non promise values', () =>
> 13 |   expect([1]).toHaveLengthAsync(Promise.resolve(1)));
  14 |
  15 | it('works with expected non promise values and not', () =>
  16 |   expect([1, 2]).not.toHaveLengthAsync(Promise.resolve(1)));
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/expect-async-matcher/__tests__/success.test.js:13
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/failures/__tests__/asyncFailures.test.js:11 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/failures/__tests__/asyncFailures.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/failures/__tests__/asyncFailures.test.js#L11)

```js
   9 |
  10 | test('resolve, but fail', () =>
> 11 |   expect(Promise.resolve({foo: 'bar'})).resolves.toEqual({baz: 'bar'}));
  12 |
  13 | test('reject, but fail', () =>
  14 |   expect(Promise.reject({foo: 'bar'})).rejects.toEqual({baz: 'bar'}));
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/failures/__tests__/asyncFailures.test.js:11
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/filter/__tests__/bar.test.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/filter/__tests__/bar.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/filter/__tests__/bar.test.js#L9)

```js
   7 | 'use strict';
   8 |
>  9 | test('stub', () => expect(2).toBe(2));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/filter/__tests__/bar.test.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/filter/__tests__/foo.test.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/filter/__tests__/foo.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/filter/__tests__/foo.test.js#L9)

```js
   7 | 'use strict';
   8 |
>  9 | test('stub', () => expect(1).toBe(1));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/filter/__tests__/foo.test.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshot.test.js:10 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshot.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/snapshot-escape/__tests__/snapshot.test.js#L10)

```js
   8 |
   9 | // prettier-ignore
> 10 | test('escape strings', () => expect('one: \\\'').toMatchSnapshot());
  11 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshot.test.js:10
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshotEscapeRegex.js:11 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshotEscapeRegex.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/snapshot-escape/__tests__/snapshotEscapeRegex.js#L11)

```js
   9 | const regex = /\dd\ \s+ \w \\\[ \. blahzz.* [xyz]+/;
  10 |
> 11 | test('escape regex', () => expect(regex).toMatchSnapshot());
  12 |
  13 | test('escape regex nested in object', () => {
  14 |   const objectContainingRegex = {regex};
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshotEscapeRegex.js:11
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshotEscapeSubstitution.test.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshotEscapeSubstitution.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/snapshot-escape/__tests__/snapshotEscapeSubstitution.test.js#L9)

```js
   7 | 'use strict';
   8 |
>  9 | test('escape substitution', () => expect('${banana}').toMatchSnapshot());
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/snapshot-escape/__tests__/snapshotEscapeSubstitution.test.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/foo.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/test-in-root/foo.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/test-in-root/foo.js#L9)

```js
   7 |
   8 | // This test shouldn't run
>  9 | test('stub', () => expect(1).toBe(2));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/foo.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/footest.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/test-in-root/footest.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/test-in-root/footest.js#L9)

```js
   7 |
   8 | // This test shouldn't run
>  9 | test('stub', () => expect(1).toBe(2));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/footest.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/spec.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/test-in-root/spec.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/test-in-root/spec.js#L9)

```js
   7 |
   8 | // This test should run
>  9 | test('stub', () => expect(1).toBe(1));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/spec.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/test.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/test-in-root/test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/test-in-root/test.js#L9)

```js
   7 |
   8 | // This test should run
>  9 | test('stub', () => expect(1).toBe(1));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-in-root/test.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-name-pattern/__tests__/testNamePattern.test.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/test-name-pattern/__tests__/testNamePattern.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/test-name-pattern/__tests__/testNamePattern.test.js#L9)

```js
   7 | 'use strict';
   8 |
>  9 | test('should match 1', () => expect(1).toBe(1));
  10 | test('should match 2', () => expect(1).toBe(1));
  11 | test('should not match 1', () => expect(1).toBe(1));
  12 | test('wisconsin', () => expect(1).toBe(1));
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-name-pattern/__tests__/testNamePattern.test.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-results-processor/__tests__/processor.test.js:9 Rule: "jest/prefer-expect-assertions"`
-   Path: `fakeNetflix/facebook-repo-jest/e2e/test-results-processor/__tests__/processor.test.js`
-   [Link](https://github.com/fakeNetflix/facebook-repo-jest/blob/HEAD/e2e/test-results-processor/__tests__/processor.test.js#L9)

```js
   7 | 'use strict';
   8 |
>  9 | test('should match 1', () => expect(1).toBe(1));
  10 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/fakeNetflix/facebook-repo-jest/e2e/test-results-processor/__tests__/processor.test.js:9
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ComputedResolver.test.js:4 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ComputedResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/ComputedResolver.test.js#L4)

```js
  2 |
  3 | test('resolverType is computed', () =>
> 4 |     expect(ComputedResolver.resolverType).toBe('computed'));
  5 |
  6 | test('telltale exists', () => expect(ComputedResolver.telltale).toBeDefined());
  7 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ComputedResolver.test.js:4
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ConditionalResolver.test.js:4 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ConditionalResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/ConditionalResolver.test.js#L4)

```js
  2 |
  3 | test('resolverType is conditional', () =>
> 4 |     expect(ConditionalResolver.resolverType).toBe('conditional'));
  5 |
  6 | test('telltale exists', () =>
  7 |     expect(ConditionalResolver.telltale).toBe('when'));
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ConditionalResolver.test.js:4
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/FileResolver.test.js:4 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/FileResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/FileResolver.test.js#L4)

```js
  2 |
  3 | test('resolverType is file', () =>
> 4 |     expect(FileResolver.resolverType).toBe('file'));
  5 |
  6 | test('telltale exists', () => expect(FileResolver.telltale).toBeDefined());
  7 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/FileResolver.test.js:4
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/InlineResolver.test.js:4 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/InlineResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/InlineResolver.test.js#L4)

```js
  2 |
  3 | test('resolverType is inline', () =>
> 4 |     expect(InlineResolver.resolverType).toBe('inline'));
  5 |
  6 | test('telltale exists', () => expect(InlineResolver.telltale).toBeDefined());
  7 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/InlineResolver.test.js:4
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ProxyResolver.test.js:12 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ProxyResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/ProxyResolver.test.js#L12)

```js
  10 |
  11 | test('resolverType is proxy', () =>
> 12 |     expect(ProxyResolver.resolverType).toBe('proxy'));
  13 |
  14 | test('telltale is target', () => expect(ProxyResolver.telltale).toBe('target'));
  15 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ProxyResolver.test.js:12
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ServiceResolver.test.js:17 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ServiceResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/ServiceResolver.test.js#L17)

```js
  15 |
  16 | test('resolverType is service', () =>
> 17 |     expect(ServiceResolver.resolverType).toBe('service'));
  18 |
  19 | test('telltale exists', () => expect(ServiceResolver.telltale).toBeDefined());
  20 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/ServiceResolver.test.js:17
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/TemplateResolver.test.js:5 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/TemplateResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/TemplateResolver.test.js#L5)

```js
  3 |
  4 | test('resolverType is file', () =>
> 5 |     expect(TemplateResolver.resolverType).toBe('template'));
  6 |
  7 | test('telltale exists', () => expect(TemplateResolver.telltale).toBeDefined());
  8 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/TemplateResolver.test.js:5
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/UrlResolver.test.js:3 Rule: "jest/prefer-expect-assertions"`
-   Path: `magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/UrlResolver.test.js`
-   [Link](https://github.com/magento/pwa-studio/blob/HEAD/packages/upward-js/lib/resolvers/__tests__/UrlResolver.test.js#L3)

```js
  1 | const UrlResolver = require('../UrlResolver');
  2 |
> 3 | test('resolverType is url', () => expect(UrlResolver.resolverType).toBe('url'));
  4 |
  5 | test('telltale exists', () => expect(UrlResolver.telltale).toBeDefined());
  6 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/magento/pwa-studio/packages/upward-js/lib/resolvers/__tests__/UrlResolver.test.js:3
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

## Rule: jest/prefer-expect-assertions

-   Message: `Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/mithi/hexapod/src/tests/isStable.test.js:12 Rule: "jest/prefer-expect-assertions"`
-   Path: `mithi/hexapod/src/tests/isStable.test.js`
-   [Link](https://github.com/mithi/hexapod/blob/HEAD/src/tests/isStable.test.js#L12)

```js
  10 | ]
  11 | test.each(cases)("test isStable:", example =>
> 12 |     expect(isStable(example.p0, example.p1, example.p2)).toBe(example.answer)
  13 | )
  14 |
```

```
Error: Could not find BlockStatement - please file a github issue at https://github.com/jest-community/eslint-plugin-jest
Occurred while linting /github/workspace/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/mithi/hexapod/src/tests/isStable.test.js:12
Rule: "jest/prefer-expect-assertions"
    at isFirstStatement (/github/workspace/lib/rules/prefer-expect-assertions.js:27:9)
    at CallExpression (/github/workspace/lib/rules/prefer-expect-assertions.js:188:40)
    at ruleErrorHandler (/github/workspace/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/github/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/github/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

</details>

### PR DESCRIPTION
**Pull request by G-Rath**
Resolves #1204

### CODE REVIEW

File: src/rules/prefer-expect-assertions.ts [hunk 1]
```diff
@@ -52,10 +52,10 @@ type MessageIds =
...
   | 'suggestRemovingExtraArguments';
 
-const suggestions: Array<[MessageIds, string]> = [
-  ['suggestAddingHasAssertions', 'expect.hasAssertions();'],
-  ['suggestAddingAssertions', 'expect.assertions();'],
-];
+// const suggestions: Array<[MessageIds, string]> = [
+//   ['suggestAddingHasAssertions', 'expect.hasAssertions();'],
+//   ['suggestAddingAssertions', 'expect.assertions();'],
+// ];
```
Comment (SimenB) [inline src/rules/prefer-expect-assertions.ts:58]: why is this commented out instead of deleted?

Comment (G-Rath) [reply src/rules/prefer-expect-assertions.ts:58]: Oh whoops, cause I forgot about it 😅 will clean it up tomorrow along with a few other comments we've got lying around
